### ISSUE TITLE
Will all products in survey gdb be exported?

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Survey_Project_Export#2]
Harold has a qualification that only the expected file names will be exported.  Do we want to update this such that Maude will export all the featureclasses, tables and rastesrs?

**Comment by KellyMWhitehead** [comment]
@philipbaileynar 

Please advise. Maybe loop through SurveyGDB and find any unexpected Feature classes, Rasters, tables and dump into a "Custom" folder in the project? Probably don't need to reference in project.rs.xml.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead what layers are we talking about? I thought that the historical publish tool essentially removed all non-official layers. The new topo project includes all official layers that were in the survey GDB. Are there others I'm not thinking about?

**Comment by volkcj** [comment]
Examples would be "DEM_Originals" or DEM1, DEM2, etc. that were generated by crews.

**Comment by KellyMWhitehead** [comment]
I have coded up a simple walk function to return a list of datasets in a GDB that are not in the official list, but need to know how to proceed.

**Options**
1. Do nothing (we will retain the original gdb's as a backup).
2. Print or log this list somewhere.
3. Export these features/rasters/tables to a 'Custom' folder (in the project or elsewhere). Include or not include these in the project.rs.xml file.

Any 'custom' file will be considered lowest priority, and no warranty will be made for them in any solution. Any export of these files would be included in a try-block to avoid breaking the rest of the code.

PB, the intent of the publish tool was to do this, but after 7 years of CHaMP, some of the gdb's have things like Lidar products (from various workflows), custom data from other organization projects, or anything else.  It might be worth sending out a warning to crew supervisors about the status of these types of files?

**Comment by KellyMWhitehead** [comment]
Extra products are stored in "CustomData" folder in project, and are documented in CustomData.xml file in that folder, as well as the log file.
