### ISSUE TITLE
Release Harold as v 0.1 of Maude so Harold code is intact as downloadable package

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Survey_Project_Export#3]
Harold code has moved to Maude.  Please Release Harold code as early v of Maude before changes are committed that change Harold.

**Comment by KellyMWhitehead** [comment]
Harold is a separate script and isn't modified (though CHaMP Data module was modified, but should still work with Harold).
Just to state the obvious:
Harold = "Flat Folder" Export (But currently does not export tables and a few other features)
Maude = "Project" Export
