### ISSUE TITLE
Follow up Questions for First Version

### ISSUE THREAD

**Issue by KellyMWhitehead** [SouthForkResearch/CHaMP_Survey_Project_Export#4]
1. What "Project Name" should be used for these projects?

2. What "Project Version" should be used? (Since Maude isn't the toolbar)

3. Should an entry in log.xml be included for "Maude"?

**Comment by philipbaileynar** [comment]
1. We don't provide crews any instructions for the project name. This will appear in riverscapes, so it is relevant. I would definitely say the site name, I just don't know if we want anything else in there, such as visit ID. 
1. Go with 1.0.0 (see next point)
1. I really like this idea. Maybe something like "Survey GDB export using Maude 1.0.0". I don't think that we need a date given that each log message has a date/time associated with it.

**Comment by volkcj** [comment]
What's the project name coming from the toolbar?  Maude's project name should be the same as this, plus some 'maude' identifying info to distinguish it from the toolbar export.
