### ISSUE TITLE
How to handle Crew-Provided vs "Important" Metadata in Topo Projects

### ISSUE THREAD

**Issue by KellyMWhitehead** [SouthForkResearch/CHaMP_Survey_Project_Export#5]
All, there are a few project level metadata tags that get stored with the Topo project that contain information provided by the crew. In historic surveys this was stored in a "SurveyInfo" table, and in new surveys this is stored directly in the projectxml. Crews manually entered this information, so there is no control over what was entered. For example, for site names some crews used CBW05583-000001_yyyymmdd or CBW05583-000001_yyyymmdd_crewname etc. 

1) My concern is making sure we do not use these tags for organizing data in riverscapes.

2) Is there anything I should add to maude (i.e new tags)? I will have access to API information while batching so I could get the 'real' site, visitid, watershed etc.

3) Do we need any changes for new topo visits (i.e. include changes from #2)?

**Comment by philipbaileynar** [comment]
@KellyMWhitehead your thoroughness is appreciated. 

We will indeed be using these tags for riverscapes and its regrettable that this means work for Maude. My solution unfortunately involves more work for Maude...

1. Only store clean, official values in the mandatory project XML tags (e.g. watershed, site, visit ID etc).
1. Store the crew values from the `SurveyInfo` table in additional tags prepended with the word `Crew`. e.g. `CrewSite`, `CrewWatershed` etc. That way we can always recover them or cross check later.
1. For the official tags you will need to look them up from some source. I see 3 options:
    1. Leverage the folder where the SurveyGDB is located to deduce the watershed, site, visit ID and year. I think this is your best bet.
    1. Use some Regex techniques to get what you need from the crew values. Throw an error on non-official values and have some way of overriding them when this fails. I think this will be futile and a ton of work, although you might use a lightweight version of this approach to verify option i).
    1. Have some master text file(s) that list crew values paired with the official values. When a survey fails to use official values you could supplement the correct alias to the file and then proceed. Again, this will be messy and a lot of work.

**Comment by KellyMWhitehead** [comment]
1. @philipbaileynar or @MattReimer , please confirm the required meta tags: ```SiteID```, ```VisitID```, ```Watershed```

2. All fields exported from SurveyInfo table will have "Crew" appended to them (lol ```CrewSurveyCrew```)

3. Again, this affects 2017 visits and a solution will need to be applied there as well (add a ticket to Topo Toolbar?)

**Comment by KellyMWhitehead** [comment]
@philipbaileynar could I use the workbench to pass this info when I batch each survey? Is the database reliable for this purpose?

**Comment by philipbaileynar** [comment]
Yes the workbench has the correct information. The challenge is knowing which site/visit etc you are processing as you loop through visits in your code. If you're using the workbench to iterate over sites/visits and then grab the survey GDB then this is perfect; use the workbench database. But if you're just looping over survey GDBs on disk then the only way to know which site/visit you are processing is if the folder structure yields this information.

**Comment by KellyMWhitehead** [comment]
Adding ```Year``` as an important tag, just in case.

**Comment by volkcj** [comment]
@KellyMWhitehead  Can the source database name be added as a metadata tag, if it isn't already?

**Comment by philipbaileynar** [comment]
@KellyMWhitehead note that Toolbar version 7.0.19 changed the meta XML tags to make them riverscapes compatible. The new tags are:

```
AddMeta(nodTopLevel, "CreatedOn", DateTime.Now.ToString("o"))
AddMeta(nodTopLevel, "Region", "CRB")
AddMeta(nodTopLevel, "Site", sSiteName)
AddMeta(nodTopLevel, "Visit", nVisitID.ToString())
AddMeta(nodTopLevel, "Year", nFieldSeason.ToString())
AddMeta(nodTopLevel, "Watershed", sWatershed)
AddMeta(nodTopLevel, "StreamName", sStreamName)
AddMeta(nodTopLevel, "Program", sProgram)
AddMeta(nodTopLevel, "Protocol", sProtocol)
AddMeta(nodTopLevel, "Organization", sOrganization)
AddMeta(nodTopLevel, "SurveyCrew", sSurveyCrew)
AddMeta(nodTopLevel, "VisitType", sVisitType)
AddMeta(nodTopLevel, "SpatialReferenceName", srInfo.Name)
AddMeta(nodTopLevel, "SpatialReferenceID", srInfo.WKID.ToString)
```
