### ISSUE TITLE
Test the following visits for various exceptions

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Survey_Project_Export#7]
"1086"
"118"
"1323"
"1918"
"2019"
"206"
"2143"
"2200"
"2211"
"2214"
"2838"
"2841"
"2846"
"289"
"3422"
"4181"
"4237"
"546"
"553"
"797"
"963"

"163"
"330"
"3267"
"3274"
"3289"
"4172"
"4086"
"299"
"284"
"327"
"3459"
"1900"
"1978"
"1966"
"1975"
"1964"
"873"
"3011"

**Comment by KellyMWhitehead** [comment]
Error (Missing Datasets)

"1011"
"659"
"657"
"4159"
"1531"
"1477"
